// The first layer of @skillcdn/console (docs/architecture.md, "The package and custom
// consoles"): the vocabulary, the schemas and the client of the console's REST API, so that a
// custom UI talks to any console with types, and so that the contract has one source. No React
// here: the server and the command line import this entry point, and nothing of the pages.

export {
  ApiError,
  type ClientOptions,
  type ConsoleClient,
  createClient,
  type FetchLike,
  type FileUpload,
} from "./client.js";
export {
  DEFAULT_TOKEN_DAYS,
  EVENTS_PAGE_LIMIT,
  LIST_LIMIT,
  MAX_AGENT_LENGTH,
  MAX_ARTIFACTS_PER_RUN,
  MAX_BODY_LENGTH,
  MAX_FILE_BYTES,
  MAX_FILE_NAME_LENGTH,
  MAX_LINK_LABEL_LENGTH,
  MAX_LINKS,
  MAX_NOTE_LENGTH,
  MAX_OPTION_LABEL_LENGTH,
  MAX_OPTIONS,
  MAX_QUESTION_LENGTH,
  MAX_REPORTS_PER_RUN,
  MAX_SUMMARY_LENGTH,
  MAX_TITLE_LENGTH,
  MAX_TOKEN_DAYS,
  MAX_TOKEN_NAME_LENGTH,
  MAX_TOKENS_PER_PERSON,
  MAX_URL_LENGTH,
  MIN_OPTIONS,
} from "./limits.js";
export {
  AUTH_ROUTES,
  isSignInFailure,
  loginPath,
  REST_ROUTES,
  RETURN_TO_PARAM,
  restPath,
  SIGN_IN_FAILURES,
  SIGN_IN_PARAM,
  type SignInFailure,
  signInPath,
} from "./routes.js";
export {
  type RestAnswerInput,
  type RestArtifact,
  type RestArtifactInput,
  type RestDecision,
  type RestDecisionInput,
  type RestDecisionOption,
  type RestDecisions,
  type RestError,
  type RestEvent,
  type RestEventData,
  type RestEvents,
  type RestFile,
  type RestFileInput,
  type RestMe,
  type RestPeople,
  type RestPerson,
  type RestPersonPatch,
  type RestProvider,
  type RestReport,
  type RestReportInput,
  type RestRun,
  type RestRunEndInput,
  type RestRunInput,
  type RestRuns,
  type RestSkill,
  type RestSkills,
  type RestTask,
  type RestTaskInput,
  type RestTaskLink,
  type RestTaskPatch,
  type RestTasks,
  type RestToken,
  type RestTokenCreated,
  type RestTokenInput,
  type RestTokens,
  restAnswerInputSchema,
  restArtifactInputSchema,
  restArtifactSchema,
  restDecisionInputSchema,
  restDecisionOptionSchema,
  restDecisionSchema,
  restDecisionsSchema,
  restErrorSchema,
  restEventDataSchema,
  restEventSchema,
  restEventsSchema,
  restFileInputSchema,
  restFileSchema,
  restMeSchema,
  restPeopleSchema,
  restPersonPatchSchema,
  restPersonSchema,
  restProviderSchema,
  restReportInputSchema,
  restReportSchema,
  restRunEndInputSchema,
  restRunInputSchema,
  restRunSchema,
  restRunsSchema,
  restSkillSchema,
  restSkillsSchema,
  restTaskInputSchema,
  restTaskLinkSchema,
  restTaskPatchSchema,
  restTaskSchema,
  restTasksSchema,
  restTokenCreatedSchema,
  restTokenInputSchema,
  restTokenSchema,
  restTokensSchema,
} from "./schemas.js";
export { hasForbiddenCodePoint } from "./text.js";
export {
  ARTIFACT_KINDS,
  type ArtifactKind,
  EVENT_KINDS,
  type EventKind,
  isProviderKey,
  PERSON_ROLES,
  type PersonRole,
  PROVIDER_KEYS,
  type ProviderKey,
  RUN_ENDINGS,
  RUN_STATUSES,
  type RunEnding,
  type RunStatus,
  SKILLS_STATUSES,
  type SkillsStatus,
  TASK_PRIORITIES,
  TASK_STATES,
  type TaskPriority,
  type TaskState,
} from "./vocabulary.js";
