// The first layer of @skillcdn/console (docs/architecture.md, "The package and custom
// consoles"): the vocabulary, the schemas and the client of the console's REST API, so that a
// custom UI talks to any console with types, and so that the contract has one source. No React
// here: the server and the command line import this entry point, and nothing of the pages.

export {
  ApiError,
  type ClientOptions,
  type ConsoleClient,
  createClient,
  type DocumentFilter,
  type EventFilter,
  type FetchLike,
  type FileUpload,
  type ProjectClient,
} from "./client.js";
export {
  CONNECT_CODE_ALPHABET,
  CONNECT_CODE_LENGTH,
  isConnectCode,
  normalizeConnectCode,
} from "./connect.js";
export {
  DOCUMENT_PATH,
  documentPathsIn,
  folderOf,
  foldersAbove,
  isDocumentPath,
  isFolderPath,
  nameOf,
} from "./documents.js";
export {
  DEFAULT_TOKEN_DAYS,
  EVENTS_PAGE_LIMIT,
  LIST_LIMIT,
  MAX_AGENT_LENGTH,
  MAX_ARTIFACTS_PER_RUN,
  MAX_BODY_LENGTH,
  MAX_DOCUMENT_LENGTH,
  MAX_DOCUMENT_PATH_LENGTH,
  MAX_DOCUMENT_SEGMENT_LENGTH,
  MAX_FILE_BYTES,
  MAX_FILE_NAME_LENGTH,
  MAX_FILES_PER_DOCUMENT,
  MAX_LANGUAGE_TAG_LENGTH,
  MAX_LINK_LABEL_LENGTH,
  MAX_LINKS,
  MAX_NOTE_LENGTH,
  MAX_OPTION_LABEL_LENGTH,
  MAX_OPTIONS,
  MAX_PROJECT_DESCRIPTION_LENGTH,
  MAX_PROJECT_KEY_LENGTH,
  MAX_PROJECT_NAME_LENGTH,
  MAX_QUESTION_LENGTH,
  MAX_REPORTS_PER_RUN,
  MAX_SEARCH_LENGTH,
  MAX_SECRET_LENGTH,
  MAX_SKILLS_ADDRESS_LENGTH,
  MAX_SUMMARY_LENGTH,
  MAX_TITLE_LENGTH,
  MAX_TOKEN_DAYS,
  MAX_TOKEN_NAME_LENGTH,
  MAX_TOKENS_PER_PERSON,
  MAX_URL_LENGTH,
  MAX_VERSIONS_PER_DOCUMENT,
  MIN_OPTIONS,
} from "./limits.js";
export {
  AUTH_ROUTES,
  CLAIM_PATH,
  connectPath,
  isSignInFailure,
  loginPath,
  PROJECT_COLLECTIONS,
  type ProjectCollection,
  personTokensPath,
  projectPath,
  REST_ROUTES,
  RETURN_TO_PARAM,
  restPath,
  SIGN_IN_FAILURES,
  SIGN_IN_PARAM,
  type SignInFailure,
  signInPath,
} from "./routes.js";
export {
  type RestAnswerInput,
  type RestArtifact,
  type RestArtifactInput,
  type RestBacklink,
  type RestClaim,
  type RestClaimInput,
  type RestConnectInput,
  type RestConnection,
  type RestConnectRequest,
  type RestDecision,
  type RestDecisionInput,
  type RestDecisionOption,
  type RestDecisionPatch,
  type RestDecisions,
  type RestDocument,
  type RestDocumentFile,
  type RestDocumentInput,
  type RestDocumentLink,
  type RestDocumentSummary,
  type RestDocuments,
  type RestError,
  type RestEvent,
  type RestEventData,
  type RestEvents,
  type RestFile,
  type RestFileInput,
  type RestMe,
  type RestMember,
  type RestMemberInput,
  type RestMemberPatch,
  type RestMembers,
  type RestMePatch,
  type RestPeople,
  type RestPerson,
  type RestPersonPatch,
  type RestProject,
  type RestProjectInput,
  type RestProjectPatch,
  type RestProjects,
  type RestProvider,
  type RestReport,
  type RestReportInput,
  type RestRun,
  type RestRunEndInput,
  type RestRunInput,
  type RestRuns,
  type RestSkill,
  type RestSkills,
  type RestTask,
  type RestTaskInput,
  type RestTaskLink,
  type RestTaskPatch,
  type RestTasks,
  type RestToken,
  type RestTokenCreated,
  type RestTokenInput,
  type RestTokens,
  type RestVersion,
  type RestVersionSummary,
  type RestVersions,
  restAnswerInputSchema,
  restArtifactInputSchema,
  restArtifactSchema,
  restBacklinkSchema,
  restClaimInputSchema,
  restClaimSchema,
  restConnectInputSchema,
  restConnectionSchema,
  restConnectRequestSchema,
  restDecisionInputSchema,
  restDecisionOptionSchema,
  restDecisionPatchSchema,
  restDecisionSchema,
  restDecisionsSchema,
  restDocumentFileSchema,
  restDocumentInputSchema,
  restDocumentLinkSchema,
  restDocumentSchema,
  restDocumentSummarySchema,
  restDocumentsSchema,
  restErrorSchema,
  restEventDataSchema,
  restEventSchema,
  restEventsSchema,
  restFileInputSchema,
  restFileSchema,
  restMemberInputSchema,
  restMemberPatchSchema,
  restMemberSchema,
  restMembersSchema,
  restMePatchSchema,
  restMeSchema,
  restPeopleSchema,
  restPersonPatchSchema,
  restPersonSchema,
  restProjectInputSchema,
  restProjectPatchSchema,
  restProjectSchema,
  restProjectsSchema,
  restProviderSchema,
  restReportInputSchema,
  restReportSchema,
  restRunEndInputSchema,
  restRunInputSchema,
  restRunSchema,
  restRunsSchema,
  restSkillSchema,
  restSkillsSchema,
  restTaskInputSchema,
  restTaskLinkSchema,
  restTaskPatchSchema,
  restTaskSchema,
  restTasksSchema,
  restTokenCreatedSchema,
  restTokenInputSchema,
  restTokenSchema,
  restTokensSchema,
  restVersionSchema,
  restVersionSummarySchema,
  restVersionsSchema,
} from "./schemas.js";
export { hasForbiddenCodePoint } from "./text.js";
export {
  ARTIFACT_KINDS,
  type ArtifactKind,
  EVENT_KINDS,
  type EventKind,
  isProviderKey,
  LINK_SOURCES,
  type LinkSource,
  PERSON_ROLES,
  type PersonRole,
  PROJECT_ROLES,
  PROJECT_VISIBILITIES,
  PROVIDER_KEYS,
  type ProjectRole,
  type ProjectVisibility,
  type ProviderKey,
  RUN_ENDINGS,
  RUN_STATUSES,
  type RunEnding,
  type RunStatus,
  SKILLS_STATUSES,
  type SkillsStatus,
  TASK_PRIORITIES,
  TASK_STATES,
  type TaskPriority,
  type TaskState,
} from "./vocabulary.js";
